### ISSUE TITLE
WarioWare: Touched! - fails to boot

### ISSUE THREAD

**Issue by Simonx22** [PSI-Rockin/CorgiDS#12]
This game is crashing on boot. Tested on Windows and Ubuntu using master.
Log:
```
Save size: 8192

POWCNT1: $0000
A9 offset: $00004000 entry: $02004800 RAM: $02004000 size: $00110C78
A7 offset: $003BA800 entry: $02380000 RAM: $02380000 size: $00026A60

ITCM size: $00000000
DTCM base: $027C0000
DTCM size: $00000000
(9) Unrecognized byte read from $04000247QObject::~QObject: Timers cannot be stopped from another thread
Press <RETURN> to close this window...
```

**Comment by PSI-Rockin** [comment]
Related to #11. Ignore everything else that says "unrecognized byte read" as that's just an exit(1) call I forgot to comment out and will be fixed relatively shortly.
EDIT: It's been fixed, how does it look now?

**Comment by Simonx22** [comment]
Log with the latest master:
```
Save size: 8192

POWCNT1: $820F
A9 offset: $00004000 entry: $02004800 RAM: $02004000 size: $00110C78
A7 offset: $003BA800 entry: $02380000 RAM: $02380000 size: $00026A60

ITCM size: $00000000
DTCM base: $027C0000
DTCM size: $00000000
(9) Unrecognized byte read from $04000247
```

**Comment by PSI-Rockin** [comment]
Wow, I should read the log more closely. 0x04000247 is a valid I/O register. Anyway, I made it accessible for both CPUs now.

**Comment by Simonx22** [comment]
Nope, it's not doing anything now for some reason.
![image](https://user-images.githubusercontent.com/26326692/34342396-380d5aba-e9af-11e7-8e1e-307239bff935.png)

**Comment by PSI-Rockin** [comment]
I don't know what the problem could be then, so I'm gonna have to get a copy of this and test it myself in the future.

**Comment by Simonx22** [comment]
Fixed with https://github.com/PSI-Rockin/CorgiDS/commit/64e32f379a0f9985f872cca39d3046cdc2ea95cd
