### ISSUE TITLE
Cannot proceed because libwinpthread-1.dll was not found.

### ISSUE THREAD

**Issue by win0na** [PSI-Rockin/CorgiDS#15]
When I launch the program, I am greeted with the following error.

    The code execution cannot proceed because libwinpthread-1.dll was not found.
    Reinstalling the prorgram may fix this problem.

Is the pthread DLL not included in the release RAR file?

I am testing this on Windows 10 Pro x64.

**Comment by PSI-Rockin** [comment]
I snagged a copy of the DLL and updated the release. See if that works.

**Comment by win0na** [comment]
Now it returns this error, probably because you snagged the DLL from somewhere else instead of building it (at least that's what I'm assuming you did).

![ilyix2c](https://user-images.githubusercontent.com/4269491/34343754-4116243e-e9a0-11e7-8d6c-ceeed90aefe0.png)

**Comment by Simonx22** [comment]
Huh, weird. I will take a look at that when I'm at home.

**Comment by PSI-Rockin** [comment]
Well, this is unfortunate... I can't build it myself, as I don't own a Windows machine. I'll see if someone else can make a build.

**Comment by Simonx22** [comment]
See new comment

**Comment by PSI-Rockin** [comment]
@Simonx22 Someone else got a build, I uploaded it to the release.

@winneon Can you confirm if the new release build works?

EDIT: Never mind.

**Comment by Simonx22** [comment]
Alright, after "some" minutes of trying the issue is solved. It works on my end now. (Windows Server 2012 and Windows 10)
This is the zip: [release.zip](https://github.com/PSI-Rockin/CorgiDS/files/1586327/release.zip)

**Comment by PSI-Rockin** [comment]
Only took a little bit, but it works under WINE. I think that means everything's good now.

**Comment by win0na** [comment]
I can confirm that the release zip that @Simonx22 has linked now works.
