### ISSUE TITLE
FF3 Can't make the save file therefor it can't boot

### ISSUE THREAD

**Issue by RexenSquared** [PSI-Rockin/CorgiDS#17]
![ff3](https://user-images.githubusercontent.com/18408903/34344970-4c4f4786-e9b9-11e7-8fb3-a6d89dca6bfc.png)

The rom is NTSC-U

**Comment by PSI-Rockin** [comment]
Do you have savelist.bin? CorgiDS doesn't use heuristics to figure out the save size of games.

You can find a link to it under "Saving" on the GitHub README.

**Comment by PSI-Rockin** [comment]
I tested Final Fantasy III, and it works just fine with savelist.bin. It at the very least gets to the title screen.
