### ISSUE TITLE
Sims 2 DS freezes in-game

### ISSUE THREAD

**Issue by PSI-Rockin** [PSI-Rockin/CorgiDS#18]
#10 was fixed by commit 28ba77942938a5b987c445801be1907d2df1b54a, allowing the game to boot. However...
![sims2freeze](https://user-images.githubusercontent.com/12768103/34347174-31020076-e9ce-11e7-85c3-0b0a37d99617.png)
Freezes consistently upon getting to this screen. Possible DMA issue?

**Comment by Simonx22** [comment]
Also pressing A crashes the game.
```(9) Unrecognized halfword read from $00000000
(9) Unrecognized halfword write of $0000 to $00000000
(9) Unrecognized halfword read from $00000000
(9) Unrecognized halfword write of $0000 to $00000000
(9) Unrecognized halfword read from $00000000
(9) Unrecognized halfword write of $0000 to $00000000
(9) Unrecognized halfword read from $00000000
(9) Unrecognized halfword write of $0000 to $00000000
BOX_TEST
BOX_TEST
BOX_TEST
BOX_TEST
BOX_TEST
BOX_TEST
BOX_TEST
(9) Unrecognized halfword read from $00000000
(9) Unrecognized halfword write of $0000 to $00000000```

**Comment by Simonx22** [comment]
Fixed with https://github.com/PSI-Rockin/CorgiDS/commit/2f3b7cd86cb7bcf3b15a67e2252c749280942338
