### ISSUE TITLE
SpongeBob's Atlantis SquarePantis - doesn't boot

### ISSUE THREAD

**Issue by Simonx22** [PSI-Rockin/CorgiDS#22]
https://pastebin.com/Swqm1tLn

**Comment by Simonx22** [comment]
Fixed with https://github.com/PSI-Rockin/CorgiDS/commit/876d6526ec8a217054d67ff91bd384c04d76e782.

**Comment by PSI-Rockin** [comment]
Fixed by 876d6526ec8a217054d67ff91bd384c04d76e782
