### ISSUE TITLE
Games with polygon issues

### ISSUE THREAD

**Issue by Simonx22** [PSI-Rockin/CorgiDS#24]
This is the issue for games that have polygon issues. I will update it if I find more.
Nintendogs: 
![image](https://user-images.githubusercontent.com/26326692/34409818-907c0cea-ebcc-11e7-9db2-f0659bfe2789.png)

New Super Mario Bros:
![](https://i.imgur.com/brpEiyJ.gif)

Mario Party DS:
![image](https://user-images.githubusercontent.com/26326692/34462853-0307c7a4-ee4d-11e7-90fe-a4396c63c26c.png)

The Sims 2: Castaway:
![image](https://user-images.githubusercontent.com/26326692/34468501-88a37cd8-ef0a-11e7-8b4f-514d4553d9f6.png)

**Comment by PSI-Rockin** [comment]
aka Spiky Polygon Syndrome
Final Fantasy III and IV as well as Dragon Quest IX also have this issue.

**Comment by JBoughter** [comment]
Somewhat unrelated, but Mario Party DS has an issue with the way it crops the top image. 
![clover_2018-01-01_20-02-51](https://user-images.githubusercontent.com/1747240/34472370-cb35c99c-ef2e-11e7-91f0-10de826477f7.png)

Left shows the proper top screen image with proper cropping/position, right shows CorgiDS' output.

**Comment by PSI-Rockin** [comment]
@JBoughter That's just an issue with the frontend. There's a partial fix for it in the v0.2 branch, but all games are cut off at the top for every operating system with a menubar on the window.

**Comment by PSI-Rockin** [comment]
56e886167f544d1e7d11f73960ae2723a5339c81 fixes the polygon issues with New Super Mario Bros, Final Fantasy IV, and Dragon Quest IX. @Simonx22 could you test the other games and see how they're affected?

**Comment by Simonx22** [comment]
Nintendogs: works
New Super Mario Bros: works
Mario Party DS: works much better now
The Sims 2: Castaway: still broken as before

**Comment by Simonx22** [comment]
Fixed with https://github.com/PSI-Rockin/CorgiDS/commit/dcff5ec696c9fff00450e661e4e2e91ecb75f132
