### ISSUE TITLE
New Super Mario Bros. - minigame is doing weird things

### ISSUE THREAD

**Issue by Simonx22** [PSI-Rockin/CorgiDS#27]
It's flickering much faster, it was just too fast for the GIF.
![2017-12-29_17-34-56](https://user-images.githubusercontent.com/26326692/34441916-04fada4a-ecbf-11e7-9e15-10a2475da0b1.gif)

Log: 
```
POWCNT1: $020F
POWCNT1: $820F
POWCNT1: $020F
POWCNT1: $820F
POWCNT1: $020F
POWCNT1: $820F
POWCNT1: $020F
POWCNT1: $820F
POWCNT1: $020F
POWCNT1: $820F
POWCNT1: $020F
POWCNT1: $820F
POWCNT1: $020F
POWCNT1: $820F
POWCNT1: $020F
POWCNT1: $820F
POWCNT1: $020F
```

**Comment by PSI-Rockin** [comment]
Looks like the game uses 3D on both screens.

The DS is weird about that. It only supports 3D on one screen natively, so games use the display capture unit in order to get a 3D image on both screens. I only have minimal support for it, so it's not surprising that this would have problems.

**Comment by Simonx22** [comment]
Fixed with https://github.com/PSI-Rockin/CorgiDS/commit/56e886167f544d1e7d11f73960ae2723a5339c81
