### ISSUE TITLE
Compiling on Linux

### ISSUE THREAD

**Issue by robozman** [PSI-Rockin/CorgiDS#3]
The method I used was

Edit: Copied the wrong instructions (Thanks @Simonx22 )
```
git clone https://github.com/PSI-Rockin/CorgiDS
cd CorgiDS
mkdir build && cd build
qmake ../CorgiDS/CorgiDS.pro
make
```

Compiled and ran fine for me (Arch Linux)
Have yet to test any games

**Comment by Simonx22** [comment]
I tried your method on Ubuntu but it didn't work, so I tried to do something else:
```
git clone https://github.com/PSI-Rockin/CorgiDS
cd CorgiDS/CorgiDS
qmake CorgiDS.pro
make
```
It ran fine until it said this:
```
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from ‘void (QAction::*)(bool)’ to ‘const char*’
Makefile:565: recipe for target 'emuwindow.o' failed
make: *** [emuwindow.o] Error 1
```

**Comment by PSI-Rockin** [comment]
Simonx22, looks like you have Qt 4 installed. The project was made using Qt 5.9, so my bad in that regard. I'll edit the README to reflect that dependency.

**Comment by AniLeo** [comment]
With qt5-default installed and the commands by @Simonx22 it builds fine on Ubuntu 17.04

![image](https://user-images.githubusercontent.com/10283761/34320307-2731fc3a-e7ef-11e7-92c8-e3e10e2088bb.png)

**Comment by PSI-Rockin** [comment]
AniLeo, how well does running a ROM work?

**Comment by cpba** [comment]
Builds fine on fedora 27.

Couldn't get mario kart to run, it hogs a full cpu thread but doesn't display anything:

![corgids_screenshot](https://user-images.githubusercontent.com/11727844/34321624-e248b4cc-e813-11e7-9946-bc528f8830cc.png)

Could be my rom.

EDIT: The build process is very straightforward, but I'm adding it just in case anybody had trouble with it.

```
git clone https://github.com/PSI-Rockin/CorgiDS
cd CorgiDS/CorgiDS
qmake-qt5 CorgiDS.pro
make
```

**Comment by PSI-Rockin** [comment]
I doubt it's your ROM. The reason it's hogging the CPU is because of the halfword read logging; in this case, the ARM7 CPU is reading from addresses not mapped to any valid memory.
What does the beginning of the log say? There should be some information related to loading the ROM and such.

**Comment by cpba** [comment]
Oh yeah, it runs:

![mkds_corgids](https://user-images.githubusercontent.com/11727844/34321807-9a6c3a08-e817-11e7-904f-08ff3e0b294b.png)

It's actually quite a silly bug, the labels for the input boxes show up mixed. The arm7 input box is labelled arm9 while the arm9 one is labelled arm7.

It's also way too small to be playable on a hidpi screen, but I'm sure you haven't even started worrying about this.

Do you want me to report these as issues?

**Comment by PSI-Rockin** [comment]
...oh wow. I never even noticed since the paths are still saved normally.
No worries about the first one, it's a really simple fix. But do report the hidpi issue.

**Comment by cpba** [comment]
Sure, it's just that `label_2` is for some reason declared before `label` in `configwindow.ui`, the file dialog displays the correct name.

**Comment by PSI-Rockin** [comment]
I pushed new changes to address that. If anyone else was getting those errors, please report what happens now.

**Comment by AniLeo** [comment]
With f30841b53fb604018a9140201cf25f6eb15cc892

![image](https://user-images.githubusercontent.com/10283761/34322800-cbb250b8-e829-11e7-93ca-911cf8fb46f1.png) ![image](https://user-images.githubusercontent.com/10283761/34322823-4345a404-e82a-11e7-975f-64870114e71b.png)

**Comment by PSI-Rockin** [comment]
Awesome! Are there any other issues on Linux systems people are having? If not, I'll close this issue.

**Comment by awlnx** [comment]
please  include dependencies in the readme

**Comment by PSI-Rockin** [comment]
@awlnx The dependencies are listed under "Compiling" in README.

**Comment by awlnx** [comment]
sorry I noticed after I posted, anyway I have qt 5.9 installed and it still fails

/ui_configwindow.h:13:10: fatal error: QtGui/QAction: No such file or directory
 #include <QtGui/QAction>
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:1061: recipe for target 'configwindow.o' failed
make: *** [configwindow.o] Error 1

I think that's a dependency error.
The qt5-default package is installed (debian)

**Comment by PSI-Rockin** [comment]
I'll take a look at this when I wake up tomorrow, unless you've figured it out before then.

**Comment by awlnx** [comment]
I reread the comments, and followed what simon did. The program compiles and opens, but the menus are not openable

**Comment by cpba** [comment]
> The program compiles and opens, but the menus are not openable

This sounds like issue #2, which should already be fixed in the `fix_windows` branch.

**Comment by PSI-Rockin** [comment]
fix_windows has been merged with master, so the menubar should work now. Since it seems everything else is working on the Linux end, I'll close this issue.
