### ISSUE TITLE
Sims 2 DS - door disappears if you're too far away

### ISSUE THREAD

**Issue by Simonx22** [PSI-Rockin/CorgiDS#30]
![2018-01-06_17-16-47](https://user-images.githubusercontent.com/26326692/34641476-8a4729dc-f305-11e7-9c4a-ce219326ebc1.gif)

**Comment by PSI-Rockin** [comment]
I recall seeing an issue like this for melonDS. I believe the issue is with box tests?

Pokemon Diamond also has problems with houses disappearing ever since I re-enabled box tests, so I'll look into this.

**Comment by Simonx22** [comment]
Fixed with https://github.com/PSI-Rockin/CorgiDS/commit/a763a25e44805f1e8fe5c72b5b20e956e1d2daee
