### ISSUE TITLE
Add flatpak build for linux

### ISSUE THREAD

**Issue by cpba** [PSI-Rockin/CorgiDS#37]
Flatpak allows for creating application builds that will run on multiple linux distributions. It doesn't work in the same way, but you can think of it as a linux equivalent of mac os x .app bundles or android's apk.

**I have already prepared a build here:**

https://github.com/cpba/CorgiDS/releases/download/v0.1/corgids.flatpak

If this is something you'd like to have going forward, I will prepare a pull request with the metadata and flatpak manifest files. This way I won't need to build them from my forked repository.

**Comment by PSI-Rockin** [comment]
Hi, thanks for the build. I haven't been able to test it, but the v0.2 release is soon, so this came at a right time. Go ahead and send a pull request; I'll merge it when I'm finished with everything else.

**Comment by cpba** [comment]
Great! It's here:

https://github.com/PSI-Rockin/CorgiDS/pull/38

Excuse the dirtiness, it really should only have been a single commit.

**Comment by PSI-Rockin** [comment]
Closing this issue to move discussion to the pull request.
