### ISSUE TITLE
MKDS missing course labels

### ISSUE THREAD

**Issue by robozman** [PSI-Rockin/CorgiDS#8]
![mkds-missing_track_labels](https://user-images.githubusercontent.com/4441464/34323140-c0ed5dac-e7f8-11e7-8e29-e61592755547.png)
I think that the bars on the top screen are supposed to display the names of the tracks and they seem to be missing
(Arch Linux / i3)

**Comment by PSI-Rockin** [comment]
This is true; the course names should be visible. I'll look into this.

**Comment by PSI-Rockin** [comment]
Fixed in a5b3d208f0bfdc252e347d089728f6c3c7673864
